import Head from 'next/head';
import Image from 'next/image';
import styles from '../styles/Home.module.css';
import { GetStaticProps, GetStaticPaths, GetServerSideProps } from 'next';
import { useRouter } from 'next/router';

export default function Home({ hts2Data }: { hts2Data: any }) {
  const router = useRouter()
  const pushToHts4 = (hts4Code: string) => {
    router.push(`/${hts4Code}`)
  };
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      {hts2Data?.map((el: any) => {
        return (
          <ul key={el._id}>
            <li onClick={() => pushToHts4(el.code.slice(2))}>
              {el.code.slice(2)} - {el.description}
            </li>
          </ul>
        );
      })}
    </div>
  );
}
// export async function getStaticPaths() {
//   return {
//     paths: [
//       {
//         params: {
//           hts4: '01',
//         },
//       },
//     ],
//     fallback: true 
//   };
// }
// export const getStaticProps: GetStaticProps = async ({params}) => {
//   const res = await fetch(`https://hts-api.dripcapital.com/api/hts6/hts4/01${params?.hts4}`);
//   console.log(`https://hts-api.dripcapital.com/api/hts6/hts4/01${params?.hts4}`)
//   const data = await res.json();
//   console.log(data)
//   return {
//     props: {
//       hts2Data: data,
//     },
//   };
// };
export const getServerSideProps: GetServerSideProps = async ({params}) => {
  const res = await fetch(`https://hts-api.dripcapital.com/api/hts6/hts4/01${params?.hts4}`);
    const data = await res.json();
    return {
      props: {
        hts2Data: data,
      },
    };
}
